# Generated by Django 2.2.4 on 2019-09-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ('name',)},
        ),
    ]
